### ISSUE TITLE
reference for other species

### ISSUE THREAD

**Issue by lpantano** [sararselitsky/tDRmapper#2]
Hi!

I would like to support other species as well, at least maybe mouse data.
where did you get the tRNA sequences in that format? any way to get the one for mouse in the same format?

thanks!

**Comment by sararselitsky** [comment]
The way the included human FASTA file was generated was:
Downloaded tRNA FASTA from GtRNAdb (link for mouse: http://gtrnadb.ucsc.edu/genomes/eukaryota/Mmusc10/mm10-tRNAs.fa)

For mature:
a) Reformatted the header of the mature sequences to be >tRNA_name \t predicted_anti-codon_positions
b) Removed predicted introns
c) added CCA to the tail
The GtRNAdb has been updated since I made the FASTA and I don't know where to predicted anti-codon or intron data is. I will let you know when I find out.

For pre-tRNA
a) added 40 nts upstream and downstream of the predicted tRNA sequence and added a "pre" to the name. The naming scheme is described in detail in the "Naming tDRs" section (b) of the README. 

Then these two files are combined together into one FASTA file.

While answering the question, I realized how long this process is. I will work on making the scripts available that I used so others can easily make these FASTAs, as well as provide FASTAs for commonly used organisms.

Let me know if you have any other questions.

**Comment by lpantano** [comment]
oh! thanks.

shame they changed the format. I see that you can download the output tRNAscan-se, and there you have the bed file for the pre-tRNA (maybe, since I see introns there).
about the predicted anti-codon ... there i am little lost. sorry I can not help.
If you do the script it would be awesome, I can add that to `cloudbiolinux`, what we use to install tools and genomic data. I can easy implement you method there as a ggd-recipe (https://github.com/chapmanb/cloudbiolinux/tree/master/ggd-recipes) for each specie we can do.

thanks a lot for your time!!!!

**Comment by lpantano** [comment]
also, i just saw the file `mm10-tRNAs.ss.sort` has all the information you need. needs more parsing than a fasta file though.
